paths:
  /room/create:
    post:
      summary: Create a new room (Admin only)
      tags:
        - Room Management
      description: Create a new room. This endpoint is only accessible by admin users.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/room'
      responses:
        '201':
          description: Room created successfully.
        '401':
          description: Unauthorized. Admin access required.
        '403':
          description: Forbidden. Token missing or invalid.
        '400':
          description: Bad Request. Invalid user input.
        '500':
          description: Internal server error.
  /room/getRooms:
    get:
      summary: Get a list of users (Admin and Users)
      tags:
        - Room Management
      description: Retrieve a list of rooms. This endpoint is only accessible by admin users.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            default: 1
          # description: Page number for pagination (default: 1)
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          # description: Number of items per page (default: 10)
      responses:
        '200':
          description: Successful response.
        '401':
          description: Unauthorized. Admin access required.
        '403':
          description: Forbidden. Token missing or invalid.
        '500':
          description: Internal server error.

components:
  schemas:
    room:
      type: object
      properties:
        room_noS:
          type: string
          maxLength: 3
          example: A101
        room_description:
          type: string
          example: Spacious suite with a view.
        room_size:
          type: string
          maxLength: 1
          example: L
        room_price:
          type: number
          example: 150
        room_availability:
          type: boolean
          example: true
      required:
        - room_noS
        - room_description
        - room_size
        - room_price
        - room_availability

    
